data= {
    tours:[
        {
          _id: '1',
          category: ["resort", "trăng mật", "thành phố", "ngoài nước"],
          image: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image2: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image3: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image4: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          alt: "blah blah",
          title: "Bali - Brunei",
          subtitle: " 6 ngày, 5 đêm",
          context: "Trong số hàng nghìn đảo lớn nhỏ của đất nước Indonesia, Bali nổi lên như một viên kim cương rực rỡ. Nơi đây được du khách ưu ái đặt tên là thiên đường nhiệt đới.Bali, hòn đảo nhiệt đới xinh đẹp của Indonesia trở thành một trong những điểm du lịch nổi tiếng nhất châu Á. Trong năm 2012 đảo đã đón 2,8 triệu lượt khách du lịch, chủ yếu đến từ các nước châu Âu. Bali thu hút du khách bởi cảnh biển xinh đẹp, vùng đất giàu văn hóa với nhiều lễ hội và những ngôi đền đẹp nằm trên biển. Bay bằng Singapore Airlines, du khách sẽ quá cảnh tại sân bay Changi rồi nhanh chóng tới Bali, nơi chứa đựng vô vàn điều mới lạ. Trong các ấn phẩm hướng dẫn du lịch, yếu tố nghệ thuật luôn được nhấn mạnh khi giới thiệu về Bali. Hướng dẫn viên của Vietrantour sẽ đưa bạn tiếp cận tới thế giới của nghệ thuật dân gian Bali. Sáng tạo nghệ thuật là thuộc tính của hòn đảo xinh đẹp này. Nơi đây có hàng nghìn, hàng vạn ngôi đền. Tất cả đều có cổng mô phỏng theo hình tượng núi thần Meru tách làm đôi, mở ra bên trong một không gian thành kính.Trong đó, đền Tanah Lot nổi tiếng về sự linh thiêng và độc đáo. Tới đây, bạn sẽ được chiêm ngưỡng một ngôi đền bị thủy triều làm cách ly giữa làn nước vào buổi sáng. Hành trình sẽ tiếp nối với việc ghé thăm Royal Temple, ngôi đền cổ của vương triều Mengwi có kiến trúc hoàn hảo; khu lăng mộ Gunungkawi Kingstombs và đền suối nước Tirta Empul - nơi được tương truyền có dòng nước khiến con người trẻ mãi không già. Thật ra, trường sinh bất lão về mặt thể xác luôn là mộng tưởng xa vời, nhưng giữ nguyên sự trẻ trung về mặt tinh thần lại không quá khó. Du khách có thể nhận ra điều này trong hành trình khám phá Bali khi tới làng Văn hóa dân tộc Batubulan, một làng quê xinh xắn có vũ điệu Barong và Keris truyền thống. Ở đây, bạn sẽ đón nhận làn gió mát trên cao nguyên Kitamani cao 1.500m so với mực nước biển, ngắm nhìn toàn cảnh tráng lệ của ngọn núi lửa và lòng hồ Batur. Ngắm nhìn cảnh sắc, cảm nhận sự hòa quyện kỳ vĩ của trời và đất, nhiều người cảm nhận được điều tạo nên sức sáng tạo nghệ thuật của người Bali, nhất là tại các làng Mas và Ubud. Tại đây, nghệ nhân dân gian sử dụng vật liệu thép, thủy tinh, gỗ, đá, mây, tre… để tạo nên hàng nghìn chủng loại vật phẩm mang đậm dấu ấn bản địa rất được du khách ưa chuộng.Du khách phương Tây tới Bali rất thích lướt sóng, còn người Việt Nam thường dành thời gian cho thú mua sắm, tắm biển. Quanh đảo có hàng trăm bờ cát lớn nhỏ, nơi nào cũng phù hợp để thư giãn dưới ánh mặt trời ấm áp. Trên bờ là hàng trăm, hàng nghìn nhà hàng, quầy bar, nơi bạn tận hưởng đồ ăn Trung Hoa, Pháp, Italy, Ấn Độ… với nhiều hương vị đặc trưng. Là quốc gia Hồi giáo song Indonesia có nhịp sống khá tự do. Đảo Bali đón nhận đủ loại du khách nên sự pha trộn văn hóa càng đặc biệt, bởi vậy bất kỳ ai cũng sẽ tìm ra cho mình những điều hấp dẫn.",
        },
        {
          _id: '2',
          category: ["resort", "biển", "trong nước"],
          image: 'https://namtrhg.github.io/testing/images/condao-1.jpg',
          image2: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image3: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image4: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          alt: "blah blah",
          title: "Côn Đảo",
          subtitle: " 3 ngày, 2 đêm",
          context: "ABC"
        },
        {
          _id: '3',
          category: ["resort", "thành phố", "ngoài nước"],
          image: 'https://namtrhg.github.io/testing/images/singapore-1.jpg',
          image2: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image3: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image4: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          alt: "blah blah",
          title: "Malaysia - Singapore",
          subtitle: " 6 ngày, 5 đêm",
          context: "ABC",
        },
        {
          _id: '4',
          category: ["resort", "biển", "núi", "trăng mật", "trong nước"],
          image: 'https://namtrhg.github.io/testing/images/dltc-1.jpg',
          image2: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image3: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image4: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          alt: "blah blah",
          title: "Danh lam thắng cảnh miền Bắc",
          subtitle: " 7 ngày, 6 đêm",
          context: "ABC"
        },
        {
          _id: '5',
          category: ["thành phố", "trăng mật", "ngoài nước"],
          image: 'https://namtrhg.github.io/testing/images/hongkong-1.jpg',
          image2: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image3: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image4: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          alt: "blah blah",
          title: "Hồng Kông - Thâm Quyến - Quảng Châu",
          subtitle: " 5 ngày, 4 đêm",
          context: "ABC"
        },
        {
          _id: '6',
          category: ["trăng mật", "ngoài nước"],
          image: 'https://namtrhg.github.io/testing/images/thailan-1.jpg',
          image2: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image3: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image4: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          alt: "blah blah",
          title: "Thái Lan",
          subtitle: " 4 ngày, 3 đêm",
          context: "ABC"
        },
        {
          _id: '7',
          category: ["resort", "biển", "ngoài nước"],
          image: 'https://namtrhg.github.io/testing/images/brunei-1.jpg',
          image2: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image3: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image4: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          alt: "blah blah",
          title: "Brunei - Kota Kinabalu",
          subtitle: " 4 ngày, 3 đêm",
          context: "ABC"
        },
        {
          _id: '8',
          category: ["resort", "biển", "ngoài nước"],
          image: 'https://namtrhg.github.io/testing/images/brunei-1.jpg',
          image2: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image3: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image4: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          alt: "blah blah",
          title: "Thái Lan - Phuket",
          subtitle: " 4 ngày, 3 đêm",
          context: "ABC"
        },
        {
          _id: '9',
          category: ["resort", "thành phố", "ngoài nước"],
          image: 'https://namtrhg.github.io/testing/images/phuket-1.jpg',
          image2: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image3: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          image4: 'https://namtrhg.github.io/testing/images/bali-1.jpg',
          alt: "blah blah",
          title: "Đài Loan (Cao Hùng - Đài Trung - Nam Đầu - Đài Bắc)",
          subtitle: " Liên hệ",
          context: "ABC"
        },
    ],
}

module.exports=data