export const GET_TOURS_LIST = 'GET_TOURS_LIST'
export const GET_TOURS_DETAILS='GET_TOURS_DETAILS'
export const GET_TOURS_SAVE='GET_TOURS_SAVE'

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_LOGIN = 'USER_LOGIN'


