export const GET_PHD_LIST = 'GET_RICHEST_LIST'
export const SET_CURRENT_USER="SET_CURRENT_USER"
export const USER_SIGNIN_REQUEST = ' USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = ' USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = ' USER_SIGNIN_FAIL';
export const USER_REGISTER_REQUEST = ' USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = ' USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = ' USER_REGISTER_FAIL';
export const GET_COMMENT_LIST= '  GET_COMMENT_LIST';
export const GET_COMMENT_DETAILS = 'GET_COMMENT_DETAILS'
export const GET_PHD_DETAILS='GET_PHD_DETAILS';


